### ISSUE TITLE
Macro for profile & view

### ISSUE THREAD

**Issue by antoine-levitt** [timholy/ProfileView.jl#106]
I often use the following pattern:
```
Profile.clear()
@profile some_code()
ProfileView.view()
```
, then change something in my code and run it again. I also usually ctrl-c the `some_code()` computation because it's usually running some kind of optimization algorithm and I'm just interested in the performance of one iteration. It would be nice to make a macro that runs the above code, intercepting the ctrl-c to still display the profile view.

**Comment by timholy** [comment]
I've had bad things happen with profiling and Ctrl-C. Seems bettter to pass `iterations=1` to your opimtization algorithm.
