### ISSUE TITLE
Problem when adding package (Julia 1.0)

### ISSUE THREAD

**Issue by ErwanPiR** [timholy/ProfileView.jl#109]
Hi,

It might be a well known problem but I can't find the solution... When I try to add the package, it doesn't work.
`Pkg.add("ProfileView")`

`ERROR: Unsatisfiable requirements detected for ASTInterpreter2
ASTInterpreter2 [e6d88f4b] log:
 ├─possible versions are: 0.1.0-0.1.1 or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.1 — no versions left
   └─Atom [c52e3926] log:
     ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.1] or uninstalled
     └─restricted to versions 0.7.14 by an explicit requirement, leaving only versions 0.7.14`

I don't really undestand what's the matter here so I will be grateful if someone have a solution :)

Thanks

Erwan

**Comment by timholy** [comment]
Hit `]` to enter pkg mode and then type `rm ASTInterpreter2`. You want to use the newer packages anyway :smile:  https://julialang.org/blog/2019/03/debuggers

**Comment by ErwanPiR** [comment]
Thank you for your quick answer. Unfortunatly, it doesn't solve the problem. When I try
`rm ASTInterpreter2`
I get
` Warning: `ASTInterpreter2` not in project, ignoring
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1128
[ Info: No changes`

and after that I obviously still have the problem...

**Comment by timholy** [comment]
Try updating all packages. If necessary, temporarily remove `Atom` too and then `add` it back again after updating.
