### ISSUE TITLE
loading ProfileView.jl kills performance for runtests.jl

### ISSUE THREAD

**Issue by magerton** [timholy/ProfileView.jl#123]
I have a suite of tests for some code that I'm working on. My `runtests.jl` `include`s several different `.jl` files that have tests. Each separate `.jl` included puts its tests in a separate module. When I put `using ProfileView` within earlier `.jl` files, it absolutely kills performance (35ms to 7s) for some of the `@btime` benchmarks.

If I simply comment out the `using ProfileView`, the performance hit goes away. 

See https://github.com/magerton/ShaleDrillingLikelihood.jl/commit/6fdbe3e0021fd4677ae6d5cb83c96fe87e16595b

I've tried coming up with a MWE, but so far haven't been able to replicate the performance hit with it. I apologize for this! However, I thought I'd report this in case anyone else runs across this issue.

Here is my attempt at a MWE, which loosely follows the structure of my original `runtests.jl`

```julia
using Revise
using Base.Threads

println("using $(nthreads()) threads")

module Test1

using Test
using StatsFuns
using Random
using BenchmarkTools

@testset "test1" begin
    Random.seed!(1234)
    x = rand(10^4)
    @btime logsumexp($x)
end
end






module Test2

using Test
using StatsFuns
using Random
using BenchmarkTools
using Profile
using ProfileView


@testset "test2" begin
    Random.seed!(1234)
    x = rand(10^4)
    @btime logsumexp($x)
end

end



module Test3

using Test
using StatsFuns
using Random
using BenchmarkTools

@testset "test3" begin
    Random.seed!(1234)
    x = rand(10^4)
    @btime logsumexp($x)  # This would be where performance degradation happens... but it doesn't here
end

end
```

**Comment by timholy** [comment]
Let me guess, you're on Windows. See https://github.com/JuliaGraphics/Gtk.jl/issues/325

**Comment by magerton** [comment]
Thanks, @timholy . I sure am. I'll try running things on a different machine to see if they do better.

**Comment by timholy** [comment]
Can you try on Julia 1.3 with up-to-date packages? Gtk 1.0 got released this morning, maybe it will help?

**Comment by magerton** [comment]
Thanks, @timholy. I definitely will. Looks like ProfileViews is restricted to Gtk 0.18 -- does it need to get bumped to allow Gtk 1.0?

**Comment by timholy** [comment]
Oh shoot, yes, thanks for noticing! May take a few days to fix, currently anything using Gtk requires manual intervention in the General registry.

**Comment by timholy** [comment]
Yes, needs to be bumped. It is going to take a few more days due to errors in https://github.com/JuliaGizmos/GtkReactive.jl/pull/91. Sorry I jumped the gun and forgot about the dependencies.

**Comment by timholy** [comment]
I think the latest versions of Gtk fix this, and in any event this isn't technically a ProfileView issue.
