### ISSUE TITLE
Zoom documentation in README could be clarified.

### ISSUE THREAD

**Issue by kmsquire** [timholy/ProfileView.jl#135]
Beyond the title, I'm not sure what else to say.  

If I get some time, I'll try to debug further, but I don't know when that might be, so for now, this is mostly a flag.

**Comment by timholy** [comment]
Have you tried all the modifiers?

I see the docs are also a bit misleading: it's really CTRL-click-drag to select a zoom region via a rubber band.

**Comment by kmsquire** [comment]
I did try all the modifiers, but did not try dragging. Will do that when I get in front of a computer.

**Comment by kmsquire** [comment]
Ctrl-click + dragging works!  

After some experimenting, most of the other things work too.  I can't check the right click -> edit functionality (I don't have a mouse handy right now, and the macbook trackpad only has one button).

What doesn't seem to work (for me):
* A double click does not reset the view
* Ctrl + shift + arrow keys don't do anything (nor do other modifiers work)

For that last one, there's a always a chance that the keystrokes are being captured by something else before they get to the window.  I couldn't find anything that set those, but it's a bit tedious to try to find them, so I could have missed something.  

So it's likely that only the double click doesn't seem to work, which can be worked around that by zooming with ctrl-scroll (ctrl-swipe).

I'll make an MR that clarifies the documentation.

**Comment by timholy** [comment]
> I can't check the right click 

Right click should be equivalent to two-finger tap: https://www.cnet.com/how-to/five-ways-to-right-click-on-a-mac-trackpad/

> A double click does not reset the view

Hmm, looking at the docs, it would have been hard to be *less* clear...hold down the Ctrl key while you do it.

> Ctrl + shift + arrow keys don't do anything (nor do other modifiers work)

You're right. Here we suffer from the fact that it's almost impossible to write tests for GUIs. Can you file as a separate bug?

**Comment by kmsquire** [comment]
> Hmm, looking at the docs, it would have been hard to be less clear...hold down the Ctrl key while you do it.

:-)  Will update #136 again.

**Comment by kmsquire** [comment]
>>Ctrl + shift + arrow keys don't do anything (nor do other modifiers work)

> You're right. Here we suffer from the fact that it's almost impossible to write tests for GUIs. Can you file as a separate bug?

Sure.  Just to clarify, is this Mac-only, or are you seeing this on Linux as well?  (I think I remember that you're a Linux user...)
