### ISSUE TITLE
Profiling using, e.g. for ProfileView itself

### ISSUE THREAD

**Issue by PallHaraldsson** [timholy/ProfileView.jl#145]
[EDIT: Feel free to close, I've answered my own questions, and made a PR for fontsize. Unless you want the "gap" documented, it's about `using` more than the package.]

A.
ProfileView is great! After precompiling it, very slow.

FYI, to profile itself, the best way is:

```
julia> using Profile

julia> @profile using ProfileView
Gtk-Message: 10:37:32.872: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:37:32.872: Failed to load module "canberra-gtk-module"

# for me the default fontsize = 14 is too small, a PR to fix?
julia> ProfileView.view(fontsize = 25)

I do see a strange gap:

_include_from_serialized: line 681

    sv = ccall(:jl_restore_incremental, Any, (Cstring, Any), path, depmods)

any idea if there's something to do about it? [EDIT: this is normal.]


To compare:

B.
@profview using Gaston

has 3 gaps, one rather large: boot.jl, eval: line 331

https://github.com/JuliaLang/julia/blob/7d27fa883ca06e34863e90cae72d8e7438c108ae/base/boot.jl#L331

eval(m::Module, @nospecialize(e)) = ccall(:jl_toplevel_eval_in, Any, (Any, Any), m, e)

C.
julia> @profview using Gnuplot
[ Info: Precompiling Gnuplot [dc211083-a33a-5b79-959f-2ff34033469d]
[ Info:   Gnuplot version: 5.2.0

that gap is like 80% of the time (is it possible to get a percentage?):

events.jl, #273: line 2

I didn't immediately locate the events.jl (in Julia, rather than Gnuplot?). Might be nice to get a full path.
```

D.

Doing `using` again took a lot of time (`using` bug for julia? second `using` is sometimes, not always, slow):

Then get ca. 50% gap for: boot.jl, eval: line 331 for Gnuplot.

**Comment by PallHaraldsson** [comment]
FUI: I at least now know how to fill in the gaps:

ProfileView.view(C = true, fontsize = 30)

**Comment by timholy** [comment]
> After precompiling it, very slow.

Let me guess, you're on Windows. See Gtk issue 325 (I have it memorized now). Consider Juno or ProfileVega.jl if it's annoying. All three use FlameGraphs.jl under the hood, the only difference is the UI.

**Comment by PallHaraldsson** [comment]
Actually no, I'm on Linux. As I said, "feel free to close". I maybe wasn't too clear, but "very slow" only applied to precompiling the package, what I believe doesn't depend on platform (and not unique to this package). After great/fast, at least on Linux.

**Comment by timholy** [comment]
Gotcha. Yes, it has a lot of dependencies and Gtk in particular has gotten pretty slow to compile and load. There's been some discussion at https://github.com/JuliaGraphics/Gtk.jl/issues/466

**Comment by timholy** [comment]
This is now a pleasingly-fast package to load, so closing.
