### ISSUE TITLE
InitError after `using PyPlot`

### ISSUE THREAD

**Issue by antoine-levitt** [timholy/ProfileView.jl#147]
Not sure where to report this, but here goes. When I run julia and do `using ProfileView`, everything is fine. If however I do `using PyPlot` before, I get this:

```
julia> using PyPlot

julia> using ProfileView
ERROR: InitError: could not load library "/home/antoine/.julia/artifacts/fa3ffbf1684fe5a3a91cb831a4ef9300df958a4d/lib/libharfbuzz-gobject.so"
/home/antoine/.julia/artifacts/fa3ffbf1684fe5a3a91cb831a4ef9300df958a4d/lib/libharfbuzz-gobject.so: undefined symbol: hb_map_reference
```

**Comment by timholy** [comment]
Try https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl.

**Comment by antoine-levitt** [comment]
What do you mean by "try"? `add`ing it doesn't fix the issue.

**Comment by timholy** [comment]
> Not sure where to report this

**Comment by antoine-levitt** [comment]
Alright, will do

**Comment by timholy** [comment]
This isn't really a ProfileView issue, so closing.
