### ISSUE TITLE
@proview includes ProfileView-related Gtk events.jl

### ISSUE THREAD

**Issue by ianshmean** [timholy/ProfileView.jl#148]
Running `@profview myfunc()` gives this output, where `Gtk.jl//src/events.jl, #237: line 2` dominates.

myfunc() has no Gtk usage, so must be an artifact of 

![Screenshot from 2020-05-09 14-04-07](https://user-images.githubusercontent.com/1694067/81481415-151a7e80-91fe-11ea-9df4-805954888463.png)

julia master 44f3bb3fc6

**Comment by ianshmean** [comment]
It doesn't occur when you do this:
```
using Profile
@profile myfunc()
using ProfileView
ProfileView.view()
```
but it does if you load ProfileView before profiling:
```
using Profile, ProfileView
@profile myfunc()
ProfileView.view()
```

**Comment by ianshmean** [comment]
I can't replicate this replacing `myfunc()` with `rand()`.

This might be invalidation-related.. and an edge case.. `myfunc()` was actually calling `compilecache()` on an isolated test module that contains nothing but a single unique function and no deps. Somehow compiling that example was triggering something in Gtk.

**Comment by timholy** [comment]
I can't replicate this. Remember that `@profile` does not clear old results; you need to manually call `Profile.clear()`.

Could also be https://github.com/JuliaGraphics/Gtk.jl/issues/503? How are you starting Julia?

**Comment by timholy** [comment]
Since this isn't replicable, let's close. (Reopen if it recurs.)
