### ISSUE TITLE
UndefVarError: @profview not defined

### ISSUE THREAD

**Issue by bardo84** [timholy/ProfileView.jl#171]
Hi,
when running the package example, I get the following error

`
julia> using ProfileView

julia> @profview profile_test(1)  # run once to trigger compilation (ignore this one)
ERROR: LoadError: UndefVarError: @profview not defined
in expression starting at REPL[10]:1
`

`
(@v1.6) pkg> st ProfileView
      Status `C:\Users\xxx\.julia\environments\v1.6\Project.toml`
  [c46f51b8] ProfileView v0.6.10

help?> @profview
  No documentation found.

  Binding @profview does not exist.
`

**Comment by timholy** [comment]
@bardo84 I am guessing you're using VSCode. If so, see #172.

Out of curiousity, which Julia version are you using? If you use 1.6 (highly recommended) it gives you an error
```
julia> @profview sum(1:5)
WARNING: both ProfileView and VSCodeServer export "@profview"; uses of it in module Main must be qualified
ERROR: LoadError: UndefVarError: @profview not defined
```
which seem fairly clear *if* you know what "qualified" means. But I'm guessing you must be using an older Julia that isn't as helpful?

**Comment by bardo84** [comment]
Hi,
sorry, have a problem with github notifications.
>if you know what "qualified" means. 

Well, I don't and did not understand the Julia doc from its search with qualified main. Guessing: in a function, not main, ..

>the example was run on 1.6. But get the same when running the full example on 1.7:
```
function profile_test(n)
     for i = 1:n
         A = randn(100,100,20)
         m = maximum(A)
         Am = mapslices(sum, A; dims=2)
         B = A[:,:,5]
         Bsort = mapslices(sort, B; dims=1)
         b = rand(100)
         C = B.*b
     end
 end
 
 using ProfileView
 @profview profile_test(1)  # run once to trigger compilation (ignore this one)
 @profview profile_test(10)
```
```
julia> 

ERROR: LoadError: UndefVarError: @profview not defined   
in expression starting at o:\Julia\ProfileView_test.jl:15
in expression starting at o:\Julia\ProfileView_test.jl:15
```
But maybe most important
>I am guessing you're using VSCode. If so, see #172.

Yes - Still open?

**Comment by bardo84** [comment]
put the whole in a module, runs under VScode!
