### ISSUE TITLE
Labels don't show up with IJulia on Safari

### ISSUE THREAD

**Issue by rsrock** [timholy/ProfileView.jl#19]
And interactive features don't seem to work.  Web inspector shows three missing resources:

http://localhost/static/components/backbone/backbone-min.map
http://localhost/static/components/underscore/underscore-min.map
http://localhost/static/components/jquerry/jquerry-min.map

Chrome works fine, so this is not critical.  Mostly leaving this here so I remember ;-)

**Comment by timholy** [comment]
Still relevant?

**Comment by timholy** [comment]
Jupyter support moved to https://github.com/timholy/ProfileSVG.jl
