### ISSUE TITLE
hold the ProfileView when after executing a julia script?

### ISSUE THREAD

**Issue by chtlp** [timholy/ProfileView.jl#20]
Hi, I am profiling a Julia script with many command line arguments.  I opened the ProfileView at the end of the script by
```
ProfileView.view()
```
A window pops up but disappears soon and the script finishes. Is there any (recommended) way of holding the visualization?

**Comment by timholy** [comment]
Now it's based on Gtk, but the corresponding procedure is documented [here](https://github.com/JuliaLang/Gtk.jl#usage-without-the-repl).
