### ISSUE TITLE
Cannot use on Linux, loading takes forever

### ISSUE THREAD

**Issue by nlw0** [timholy/ProfileView.jl#207]
I was going to use `ProfileView` for the first time after a while, also the first time since 1.8.2. It's impossible to use, usually what happens is calling `using ProfileView` simply gets stuck, and the computer fan even turns on as something seems to be happening in the background. I did once manage to make a plot, so it must be a weird issue.

Installing in a blank project seems to work, though, so I would imagine some package incompatibility? How can I debug this and hopefully find a culprit?

**Comment by timholy** [comment]
Can you try 1.9-beta? For me this is not an issue at all. What platform are you on?

**Comment by timholy** [comment]
This doesn't seem to be an issue for the vast majority of users. Until there's more information, let's close this.
