### ISSUE TITLE
Function inlining

### ISSUE THREAD

**Issue by Vilin97** [timholy/ProfileView.jl#227]
I want to `@descend` into functions with type instability but can't if the function is inlined. How can I work around it? I tried the `@noinline` annotation but the function still gets inlined.
The function in question:
```
l2_error_normalized(s, x, y) = normsq(s(x), y) / sum(abs2, y)
```

**Comment by timholy** [comment]
You can start Juila with `--inline=no`. You can also `ascend` to above that call and then `descend` into the call that others got inlined into.
