### ISSUE TITLE
segfaults when mousing over call graph

### ISSUE THREAD

**Issue by simonster** [timholy/ProfileView.jl#26]
ProfileView opens and displays the call graph, but when I mouse over the window, it immediately crashes Julia with:

```
julia> ProfileView.view()

julia> error during Tk callback: error during Tk callback: 

signal (11): Segmentation fault
unknown function (ip: 1238257597)
unknown function (ip: 1238315391)
jl_apply_generic at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
showerror at replutil.jl:131
showerror at replutil.jl:81
jl_apply_generic at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
anonymous at client.jl:86
jl_f_apply at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
with_output_color at util.jl:209
jl_apply_generic at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
display_error at client.jl:84
jl_apply_generic at /usr/local/julia/usr/bin/../lib/libjulia.so (unknown line)
jl_tcl_callback at /home/simon/.julia/Tk/src/tkwidget.jl:148
TclInvokeStringCommand at /usr/lib/x86_64-linux-gnu/libtcl8.5.so.0 (unknown line)
unknown function (ip: 1997761792)
fish: Job 1, “julia” terminated by signal SIGSEGV (Address boundary error)
```

This used to work great on this system. Not sure what changed. `versioninfo()` is:

```
Julia Version 0.4.0-dev+3147
Commit 17ae66f* (2015-02-05 20:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

with ProfileView 0.0.8 and Tk 0.2.16.

**Comment by timholy** [comment]
For me this started right after the merger of the new GC. But I still haven't found a reliable sequence of events that triggers it.

**Comment by timholy** [comment]
BTW, in the absence of a fix the way I work around this is:
```julia
# (profile my code)
bt, lidict = Profile.retrieve();
using HDF5, JLD
@save "/tmp/prof.jld" bt lidict
```
Then I open a separate julia session and say
```julia
using ProfileView, HDF5, JLD
@load "/tmp/prof.jld"
ProfileView(bt, lidict=lidict)
```
When that session crashes, at least I don't lose my work.

**Comment by simeonbassett** [comment]
I've also had consistent crashes with 0.4 and windows.  It doesn't seem to be mousing over though, when I resize I get errors and eventually a crash.

**Comment by timholy** [comment]
As of a julia build from today I'm having a hard time getting it to segfault. (Not that I'm complaining...) Does this fit with anyone else's experience?

**Comment by simeonbassett** [comment]
Hi Tim, thanks for keeping up this package, it has been extremely helpful so far. I  still get crashes (now it seems to be just mouseover) and my 0.4 installation is up to date, although I only use Pkg.update().  Is there anything else I should do to get the latest?

**Comment by timholy** [comment]
No, it seems I was just getting lucky. There's still a bug to fix, that means.

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/10247
