### ISSUE TITLE
Saving profile results and ProfileViewing them later. 

### ISSUE THREAD

**Issue by zenna** [timholy/ProfileView.jl#28]
I'd like to be able to be able to view profiles from previous runs. I don't believe this is possible right now, since ProfileView.view can take as input the result of Profile.fetch().  But that value becomes invalid from one session to the next.

Is there a simple solution?

**Comment by timholy** [comment]
Yes, see the Profile docs in base julia. Use `bt, lidict = Profile.retrieve()`.

**Comment by timholy** [comment]
This is here now as a reminder to me to add a toolbar with "save as" and "open" icons.

**Comment by timholy** [comment]
Toolbar added long ago.
