### ISSUE TITLE
Tk Error when using ProfileView.view()

### ISSUE THREAD

**Issue by rcnlee** [timholy/ProfileView.jl#30]
I get this error when I try to mouse over the ProfileView window:

julia> error during Tk callback: error during Tk callback: error during Tk cal
lback:
ERROR: `width` has no method matching width(::BoundingBox)
 in anonymous at C:\Users\rcnlee\.julia\v0.3\ProfileView\src\ProfileView.jl:19
2
 in anonymous at C:\Users\rcnlee\.julia\v0.3\Tk\src\tkwidget.jl:399
 in jl_tcl_callback at C:\Users\rcnlee\.julia\v0.3\Tk\src\tkwidget.jl:145
 in tcl_doevent at C:\Users\rcnlee\.julia\v0.3\Tk\src\tkwidget.jl:20 (repeats
2 times)
 in _uv_hook_asynccb at stream.jl:489
 in process_events at stream.jl:537
 in wait at task.jl:273
 in stream_wait at stream.jl:263
 in write at stream.jl:788
 in print at ascii.jl:93
 in print at string.jl:4
 in println at string.jl:5
 in jl_tcl_callback at C:\Users\rcnlee\.julia\v0.3\Tk\src\tkwidget.jl:147
 in tcl_doevent at C:\Users\rcnlee\.julia\v0.3\Tk\src\tkwidget.jl:20 (repeats
2 times)
 in _uv_hook_asynccb at stream.jl:489
 in process_events at stream.jl:537
 in wait at task.jl:273
 in stream_wait at stream.jl:263
 in write at stream.jl:788
 in print at ascii.jl:93
 in print at string.jl:4
 in println at string.jl:5
 in jl_tcl_callback at C:\Users\rcnlee\.julia\v0.3\Tk\src\tkwidget.jl:147
 in tcl_doevent at C:\Users\rcnlee\.julia\v0.3\Tk\src\tkwidget.jl:20 (repeats
2 times)
 in _uv_hook_asynccb at stream.jl:489
 in process_events at stream.jl:537
 in wait at task.jl:273
 in wait at task.jl:194
 in stream_wait at stream.jl:263
 in wait_readnb at stream.jl:316
 in read at stream.jl:698
 in read at io.jl:133
 in anonymous at LineEdit.jl:859
 in prompt! at LineEdit.jl:1399
 in run_interface at LineEdit.jl:1374
 in run_frontend at REPL.jl:817
 in run_repl at REPL.jl:169

ProfileView is v0.0.9
Tk is v0.3.0
Windows 8
Julia 0.3.3

**Comment by timholy** [comment]
Today's my luck day...see https://github.com/timholy/ImageView.jl/issues/64#issuecomment-77258312. Fix coming momentarily.
