### ISSUE TITLE
ProfileView.view() segfaults on example in the ProfileView readme on 0.4 dev branch

### ISSUE THREAD

**Issue by macd** [timholy/ProfileView.jl#31]
Running the example exactly as in the readme for ProfileViews on dev branch of Julia (Version 0.4.0-dev+3806 (2015-03-13 01:02 UTC) Commit 5195cc8* (0 days old master)) results in the following segfault:

signal (11): Segmentation fault
jl_tcl_callback at /home/ubuntu/.julia/v0.4/Tk/src/tkwidget.jl:142
jlcapi_jl_tcl_callback_65508 at  (unknown line)
TclInvokeStringCommand at /usr/lib/x86_64-linux-gnu/libtcl8.6.so.0 (unknown line)
unknown function (ip: -531889139)
unknown function (ip: -531891278)
Tcl_FindCommand at /usr/lib/x86_64-linux-gnu/libtcl8.6.so.0 (unknown line)
unknown function (ip: 1157713040)
Segmentation fault (core dumped)

All libs were updated with Pkg.update().  This is on Ubuntu 14.04

**Comment by timholy** [comment]
This is a bug in Tk, see https://github.com/JuliaLang/julia/commit/9053bfff983bf758539968dd3322c65b4281e08c#commitcomment-10150188. I just haven't figured out the proper fix, and probably won't have time for several days (I'm immersed in some AbstractArray revamps).

**Comment by timholy** [comment]
Fixed in https://github.com/JuliaLang/Tk.jl/commit/b40081f47dd916d2fdd48c4e05590b27ce566d36
