### ISSUE TITLE
ERROR: Direction 3 not recognized

### ISSUE THREAD

**Issue by Keno** [timholy/ProfileView.jl#43]
The Gtk based ProfileView is great. Unfortunately, I hit the following bug:

```
julia> FATAL ERROR: Gtk state corrupted by error thrown in a callback:
ERROR: Direction 3 not recognized
 in scrollpm at /Users/kfischer/.julia/v0.5/GtkUtilities/src/panzoom.jl:385
 in anonymous at /Users/kfischer/.julia/v0.5/GtkUtilities/src/panzoom.jl:354
 in mousescroll_cb at /Users/kfischer/.julia/v0.5/Gtk/src/events.jl:193
 in anonymous at /Users/kfischer/.julia/v0.5/Gtk/src/events.jl:2
 in g_sigatom at /Users/kfischer/.julia/v0.5/Gtk/src/GLib/signals.jl:166
 in gtk_main at /Users/kfischer/.julia/v0.5/Gtk/src/events.jl:1
```

**Comment by timholy** [comment]
Out of curiosity, what are you doing to generate that event? I use a mousewheel, and the only possibilities are UP and DOWN. You must have generated RIGHT somehow. I can have it silently drop RIGHT and LEFT, but it seems like a better fix would be to have it do something different in such cases. (It may be as simple as assigning +1/-1 appropriately to LEFT and RIGHT in `scrollpm`.)

Hard for me to test this, so can I ask you to submit the appropriate patch?

**Comment by timholy** [comment]
Oh, and all this should be moved over to GtkUtilities, so I'll close this.

**Comment by timholy** [comment]
Helpful link: https://github.com/timholy/GtkUtilities.jl
