### ISSUE TITLE
Custom coloration & filter functions

### ISSUE THREAD

**Issue by Keno** [timholy/ProfileView.jl#44]
It would be nice to be able to provide a custom callback to color the bars in the ProfileView. This could be  used to e.g. color bars by package or look at compilation time vs inference, etc. Similarly, it would be nice to filter as well, e.g. to filter out all gc time.

**Comment by timholy** [comment]
Just to chime in that I think this is a great idea, and when less swamped (hopefully in a few days) I will look into this.

**Comment by timholy** [comment]
Fixed by https://github.com/timholy/FlameGraphs.jl and #128
