### ISSUE TITLE
InitError when compiling on windows 10

### ISSUE THREAD

**Issue by SoYman** [timholy/ProfileView.jl#49]
I get this error when I attempt to load ProfileView in a julia 0.4.2 REPL. I'm quite new to submitting issues so if you need me to do anything or provide any further information, please do tell.

julia> using ProfileView
ERROR: InitError: InitError: error compiling __init__: error compiling __init__gtype__: could not load library "C:\Users\Arnaldur\.julia\v0.4\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll"
The specified procedure could not be found.

 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
 in stale_cachefile at loading.jl:441
 in recompile_stale at loading.jl:459
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
 in stale_cachefile at loading.jl:441
 in recompile_stale at loading.jl:459
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
 in __init__ at C:\Users\Arnaldur\.julia\v0.4\ProfileView\src\ProfileView.jl:49
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at loading.jl:109
 in require at loading.jl:219
during initialization of module GLib
during initialization of module ProfileView

**Comment by timholy** [comment]
Thanks for the report. It looks like this is a [Gtk.jl](https://github.com/JuliaLang/Gtk.jl) issue (ProfileView depends on Gtk). Assuming that you get failures from `Pkg.test("Gtk")`, you should first test whether `Pkg.build("Gtk")` helps fix the problem. If not, then you should open an issue over at Gtk.

**Comment by SoYman** [comment]
Although Pkg.test("Gtk") shows less than promising results:

(julia.exe:9972): GModule-CRITICAL **: g_module_symbol: assertion 'symbol != NULL' failed
WARNING: Method definition g_type(Type{##9#T<:Gtk.GtkWidget}) in module Gtk at C:\Users\******\.julia\v0.4\Gtk\src\GLib\gtype.jl:181 overwritten in module Test at C:\Users\******\.julia\v0.4\Gtk\src\GLib\gtype.jl:181.
The following messages:
   WARNING: Error in @guarded callback
are expected and a sign of normal operation.
WARNING: Error in @guarded callback
ERROR: UndefVarError: k not defined
 [inlined code] from C:\Users\******\.julia\v0.4\Gtk\test\misc.jl:8
 in anonymous at C:\Users\******\.julia\v0.4\Gtk\src\base.jl:86
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:280
 in _start at client.jl:378
WARNING: Error in @guarded callback
ERROR: UndefVarError: k not defined
 [inlined code] from C:\Users\******\.julia\v0.4\Gtk\test\misc.jl:10
 in bar2 at C:\Users\******\.julia\v0.4\Gtk\src\base.jl:86
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:280
 in _start at client.jl:378
WARNING: Error in @guarded callback
ERROR: UndefVarError: k not defined
 [inlined code] from C:\Users\******\.julia\v0.4\Gtk\test\misc.jl:15
 in bar3 at C:\Users\******\.julia\v0.4\Gtk\src\base.jl:86
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:280
 in _start at client.jl:378
WARNING: Error in @guarded callback
ERROR: UndefVarError: k not defined
 [inlined code] from C:\Users\******\.julia\v0.4\Gtk\test\misc.jl:18
 in bar4 at C:\Users\******\.julia\v0.4\Gtk\src\base.jl:86
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:280
 in _start at client.jl:378

(julia.exe:9972): GModule-CRITICAL **: g_module_symbol: assertion 'symbol != NULL' failed
INFO: Gtk tests passed

Running Pkg.build("Gtk") seems to fix ProfileView in my case, the Gtk test errors stay the same however. Thanks for the help.
