### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by cstjean** [timholy/ProfileView.jl#56]
ProfileView is great for profiling small or medium-sized functions. But on Julia 0.4.5, OSX, in IJulia, on a more complex codebase, it can sometimes take 3 minutes+ to display the flame graph (Firefox warns me multiple times about unresponsive scripts). And then whenever I resize it (by accidentally scrolling the mouse on top of it) it takes another 30-40 seconds to settle. Is that also a problem on other platforms? What could I do to improve this, do you know where the slowdown comes from?

**Comment by timholy** [comment]
Try it first with the Gtk interface (e.g., from the REPL). Assuming it's very fast there, look into #18.

**Comment by cstjean** [comment]
Thank you for the pointers. @darwindarak's observation was correct - it's the text labels on the rectangles that slow things down. Turning them off (removing `data-shortinfo="$shortinfo"`) solves the problem entirely. I'd like to have an option `if rectangle-is-small then don't output data-shortinfo`, but I don't know SVG at all, and only a little bit of HTML. So far I've got this:

```julia
        short_info_element = (width < avgcharwidth*20 ? "" : 
                              """data-shortinfo="$shortinfo" """)
        print(f, """<rect vector-effect="non-scaling-stroke" x="$xstart" y="$y" width="$width" height="$ystep" fill="rgb($red,$green,$blue)" rx="2" ry="2" $short_info_element data-info="$info"/>\n""")
```

and it kinda works, but for some reason there are more labels that appear when I _shrink_ the image with the mouse-wheel, and I'm baffled by that behaviour. The HTML isn't recomputed at each mouse-scroll, is it? There's something about the program logic that I'm not understanding. Any suggestion is appreciated.

**Comment by cstjean** [comment]
I spoke too soon - I'm not so sure that the text labels are to blame anymore. I'm just not the right person to be working on this, sorry...

**Comment by timholy** [comment]
I'm not either, sorry.

One other workaround might be to decrease [this number](https://github.com/timholy/ProfileView.jl/blob/934ad9f354288d6d9867573865ec9b18d58455e7/src/ProfileView.jl#L81), to something like 100-1000 or so. It should greatly reduce the number of boxes it draws, but it will drop out more calls that don't add a lot to the total time.
