### ISSUE TITLE
Window management

### ISSUE THREAD

**Issue by ettersi** [timholy/ProfileView.jl#60]
The `ProfileView.view()` function opens a new window every time it is called. I personally think it would be more convenient if it instead reused the current window just like PyPlot does. If you really want to have multiple windows, we could introduce an extra function corresponding to PyPlot's `figure()`.

**Comment by tpapp** [comment]
Also, `Ctrl-Q` and/or `Ctrl-W` for closing the window would be useful — I don't know if they are "official" defaults but many Gtk applications support them.

**Comment by timholy** [comment]
I personally like having multiple windows, so I didn't implement re-use. But see #77.
