### ISSUE TITLE
Garbage colore frames no longer red?

### ISSUE THREAD

**Issue by KristofferC** [timholy/ProfileView.jl#63]
Running the example in the README (which does causes gc):

![image](https://cloud.githubusercontent.com/assets/1282691/18091423/e07085fa-6ec8-11e6-8f7c-3f127662954b.png)

I will try to figure out what the problem is sometime :)

**Comment by timholy** [comment]
I noticed this too. Moreover, in julia-0.5 "trouble" is often indicated by `*typemap*` calls, so those should probably be added to the red list.

**Comment by timholy** [comment]
Once tag v0.2.1 gets merged in METADATA, now there should be as much red as you could wish for. In a change, the red is aimed specifically at non-inferrability rather than GC.
