### ISSUE TITLE
julia crash on OS X

### ISSUE THREAD

**Issue by pagnani** [timholy/ProfileView.jl#67]
Dear Tim,

here a reproducible way to make julia crash (at least on my macbook pro)
```
using ProfileView
workspace()
using ProfileView
# and here julia crash
```
[here](https://gist.github.com/pagnani/7f423d4fab54aead40884aaff2d99d95) you can see what is printed after crashing and my `versioninfo(true)`  is [here](https://gist.github.com/pagnani/ff3b15652a60c587ce13cbee43d81162). Let me know if it is better to report upstream as a general julia issue...

Thanks

**Comment by timholy** [comment]
It's probably either a julia issue or a Gtk.jl issue. Segfaults on Linux too.

**Comment by timholy** [comment]
`workspace` has been removed, so this issue is no longer relevant.
