### ISSUE TITLE
Failing on OS X

### ISSUE THREAD

**Issue by jminardi** [timholy/ProfileView.jl#68]
I am using Julia 0.5 on OS X 10.12

When I try to view the profile for my code I get the following error:

```GdkQuartzDisplay does not implement the monitor vfuncs```

If I just `Profile.print()` I can see the tree so I know the profiler works.

**Comment by timholy** [comment]
Maybe report over at Gtk.jl?

**Comment by jminardi** [comment]
Ok, created a new issue there: https://github.com/JuliaGraphics/Gtk.jl/issues/278
