### ISSUE TITLE
Julia Crash on Window Resize

### ISSUE THREAD

**Issue by goldfita** [timholy/ProfileView.jl#70]
The example in the documentation works fine.  However, my code (which makes a c call but has never caused a problem), causes the profile graph to crash Julia when I try to resize it.  I'm also getting this error, which I don't remember having before.  Gtk may have been updated.

> (julia.exe:1996): GModule-CRITICAL **: g_module_symbol: assertion 'symbol != NULL' failed

>versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)

**Comment by timholy** [comment]
Without more information this is not actionable.

**Comment by goldfita** [comment]
I'll see if I can come up with something simple that reproduces the problem this weekend.

**Comment by goldfita** [comment]
After a bit of work, it looks as though this might be some sort of package dependency issue.  I always get the GModule-CRITICAL message, but it only crashes when I use PyPlot first.  I happened to update  packages after getting to the essence of the problem.  The update did not change the problem, but I captured the warning messages generated during the recompile in warnings_following_update.txt.

Let me know if there's any further info you need or if you want me to cross-post this report as it's now not clear that it has anything to do with ProfileView.

[packages_before_update.txt](https://github.com/timholy/ProfileView.jl/files/801217/packages_before_update.txt)
[packages_after_update.txt](https://github.com/timholy/ProfileView.jl/files/801218/packages_after_update.txt)
[crash_before_package_update.txt](https://github.com/timholy/ProfileView.jl/files/801216/crash_before_package_update.txt)
[warnings_following_update.txt](https://github.com/timholy/ProfileView.jl/files/801219/warnings_following_update.txt)

**Comment by timholy** [comment]
Does https://github.com/JuliaGraphics/Gtk.jl/issues/193 fix it?

**Comment by goldfita** [comment]
I can change backend in matplotlibrc

```
#backend      : Qt5Agg
backend      : WebAgg
```

or set it after loading PyPlot

`pygui(:tk)`

Either way fixes the crash; the error message still comes up.  Thanks!
