### ISSUE TITLE
Plot do not use the full window lenght

### ISSUE THREAD

**Issue by JonWel** [timholy/ProfileView.jl#71]
I'm using Julia 0.5.0 on Ubuntu 16.10 and ProfileView 0.1.5.

When I launch the viewer, the graph seems to only use a quarter of the available length (whatever the scale of the window).
Here is an example:
![profile](https://cloud.githubusercontent.com/assets/11057909/23092392/34de673c-f5ca-11e6-8370-bed04a838ecd.png)

It would be more convenient to fit to the full window length.

**Comment by timholy** [comment]
This is on the web version, which I don't fix but hopefully others will.

Does it affect the Gtk version too?

**Comment by JonWel** [comment]
I don't know about the web version, I"m using the package locally with:
```Julia
using ProfileView
function2test(inputs)
Profile.clear()
@profile function2test(inputs)
ProfileView.view()
ProfileView.svgwrite("profile_results.svg")
```
To me this is the GTK version.

**Comment by timholy** [comment]
So you're writing the SVG file but it's the same as what shows on the screen?

Can you give an example of how you collect that profile data? Or save it to a file? (Use the little disk icon)

Alternatively, consider adding `C=true`; I suspect there are some pure-C calls taking up much of the time.

**Comment by JonWel** [comment]
Yes, my code is calling C external library.
Seems that was the cause:
![profile](https://cloud.githubusercontent.com/assets/11057909/23093800/ee5ea056-f5ec-11e6-8307-f00c17deb714.png)

**Comment by JonWel** [comment]
But what does these 3/4 of the code means?
It seems to be linked to libpthread.
Is it simply telling my 3 other core (I have a quad core, 8 threads), are Idle?

```
/build/glibc-jxM2Ev/glibc-2.24/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S, : line 105
/lib/x86_64-linux-gnu/libpthread.so.0, : line -1
./deps/build/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8/./deps/srccache/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8/src/unix/thread.c, uv__thread_start: line 52
./src/./src/threading.c, ti_threadfun: line 386
./src/./src/threadgroup.c, ti_threadgroup_fork: line 152
./deps/build/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8/./deps/srccache/libuv-8d5131b6c1595920dd30644cd1435b4f344b46c8/src/unix/thread.c, uv_cond_wait: line 411
/lib/x86_64-linux-gnu/libpthread.so.0, pthread_cond_wait: line -1
```

**Comment by JonWel** [comment]
> So you're writing the SVG file but it's the same as what shows on the screen?

I'm using both, main difference is the yellow background. I used the SVG to have a way to display the result to you, but I could also have done a screen capture.
