### ISSUE TITLE
Loading ProfileView causes changing representation of BigFloats

### ISSUE THREAD

**Issue by giordano** [timholy/ProfileView.jl#80]
I really don't have idea why, but...
```julia
julia> ENV["LANG"]
"it_IT.UTF-8"

julia> big(1.0)
1.000000000000000000000000000000000000000000000000000000000000000000000000000000

julia> using ProfileView

julia> big(1.0)
1,000000000000000000000000000000000000000000000000000000000000000000000000000000
```
For sure `LANG` is relevant here (in Italian comma is the decimal separator), because when `LANG=C` `big(1.0)` still has point as decimal separator.  I can reproduce this issue with Julia 0.5 and 0.6 (built yesterday).

**Comment by timholy** [comment]
I can't reproduce because if I try to change my locale within julia with
```julia
julia> ENV["LANG"] = "it_IT.UTF-8"
"it_IT.UTF-8"
```
then I get
```
(process:8739): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
```
So let me ask, does this also happen with `using Gtk`? If so, let's close this here and reopen at [Gtk.jl](https://github.com/JuliaGraphics/Gtk.jl).

**Comment by giordano** [comment]
Sorry, I didn't specify it in the previous message, but changing the locale within has no effect, it must be set in the shell before running the program.  Anyway, this happens also only with `Gtk`, so I'm going to close this ticket, thanks.
