### ISSUE TITLE
StackOverflow on keypress

### ISSUE THREAD

**Issue by antoine-levitt** [timholy/ProfileView.jl#82]
When the ProfileView window is on focus and I press a key, I get

```
WARNING: Executing ProfileViewGtk.#3:
ERROR: StackOverflowError:
Stacktrace:
 [1] convert(::Type{Gtk.GdkEvent}, ::Ptr{Gtk.GdkEvent}) at /home/antoine/.julia/v0.6/Gtk/src/GLib/gtype.jl:283 (repeats 80000 times)

```
This is with julia nightly and latest versions of packages. The culprit (gtype.jl:283) is

`convert{T <: GBoxed}(::Type{T}, unbox::Ptr{T}) = T(unbox)`

(I have no idea what that is)

**Comment by timholy** [comment]
Hmm, I can't replicate this. What platform are you on? I'm Kubuntu 16.04. And to be concrete, I'm using
```julia
julia> Pkg.status("ProfileView")
 - ProfileView                   0.2.1

julia> Pkg.status("Gtk")
 - Gtk                           0.13.0

julia> Pkg.status("GtkReactive")
 - GtkReactive                   0.1.2
```

**Comment by antoine-levitt** [comment]
I have the same version as you. It works fine for v0.5 and for the alpha in https://discourse.julialang.org/t/julia-0-6-alpha-released-please-update-your-projects/2571, so we'll see if the bug survives in a couple of nightlies. Sorry for the noise, closing the bug for now.

**Comment by antoine-levitt** [comment]
Can confirm this is fixed after updating to the rc and updating all packages.
