### ISSUE TITLE
`using ProfileView` throws `UndefVarError`

### ISSUE THREAD

**Issue by daniellivingston** [timholy/ProfileView.jl#86]
Calling `using ProfileView` throws `UndefVarError: Uint not defined`, regardless of whether the package is added through `Pkg.add()` or `git clone https://github.com/timholy/ProfileView.jl.git`.

     julia> using ProfileView 
     INFO: Recompiling stale cache file /Users/livingston/.julia/lib/v0.5/Colors.ji for module Colors.
     INFO: Recompiling stale cache file /Users/livingston/.julia/lib/v0.5/Graphics.ji for module Graphics.
     INFO: Recompiling stale cache file /Users/livingston/.julia/lib/v0.5/Cairo.ji for module Cairo.
     ERROR: LoadError: LoadError: UndefVarError: Uint not defined
      in include_from_node1(::String) at ./loading.jl:488
      in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
      in include_from_node1(::String) at ./loading.jl:488
      in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
      in eval(::Module, ::Any) at ./boot.jl:234
      in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
      in require(::Symbol) at ./loading.jl:415
      in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
     while loading /Users/livingston/.julia/v0.5/ProfileView/src/pvtree.jl, in expression starting on line 9
     while loading /Users/livingston/.julia/v0.5/ProfileView/src/ProfileView.jl, in expression starting on line 36

**Comment by timholy** [comment]
There's something strange about your installation, I'm afraid. If I grep the source, there is no `Uint` in it:
```julia
tim@diva:/tmp$ git clone https://github.com/timholy/ProfileView.jl.git
Cloning into 'ProfileView.jl'...
remote: Counting objects: 483, done.
remote: Total 483 (delta 0), reused 0 (delta 0), pack-reused 483
Receiving objects: 100% (483/483), 282.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (248/248), done.
Checking connectivity... done.
tim@diva:/tmp$ cd ProfileView.jl/src/
tim@diva:/tmp/ProfileView.jl/src$ grep Uint *
tim@diva:/tmp/ProfileView.jl/src$ 
```
You might check `git log`, there should be commits as recently as Aug 22 2017.

**Comment by daniellivingston** [comment]
Very odd - I'll look into it. On line 9 in `pvtree.jl`, it reads

     type PVData
          ip::Uint           # the instruction pointer
          hspan::UnitRange{Int} # horizontal span (used as the x-axis in display)
          status::Int        # nonzero for special handling, (e.g., gc events)
     end
