### ISSUE TITLE
Frontend for Gadfly/D3?

### ISSUE THREAD

**Issue by Aerlinger** [timholy/ProfileView.jl#9]
Was reading this thread: https://github.com/timholy/ProfileView.jl/issues/2 and thought it would make sense to have a front-end renderer in Gadfly as well. This wouldn't necessarily be a replacement for the existing lightweight SVG rendering tool, but would be helpful for more powerful interactive analysis as well as D3 integration for web interaction.

Thoughts?

**Comment by timholy** [comment]
Closing because there is an existing system, and any future change should involve a pull request.
