### ISSUE TITLE
Labels not showing up correctly

### ISSUE THREAD

**Issue by rapus95** [timholy/ProfileView.jl#91]
When i run it from Atom I get corrupted labels and ctrl+left clicking doesn't zoom in onto a bar either :/
Instead when clicking on a bar the commandline output is ALWAYS `C:\Users\necka\.julia\v0.6\Atom\src\eval.jl, macro expansion: line 73
  .\task.jl, #98: line 80`
![image](https://user-images.githubusercontent.com/5960902/37005240-b8d061dc-20d3-11e8-9d59-27796d74c023.png)

**Comment by jacobadenbaum** [comment]
I'm having the same problem on Mac OSX running it from the REPL.  When I click on a bar, the output is always
```
./REPL.jl, macro expansion: line 97
  ./event.jl, #1: line 73
```

**Comment by antoine-levitt** [comment]
This is working with the workaround in https://github.com/JuliaImages/ImageView.jl/issues/139#issuecomment-366036213 (pinning Cairo to 0.4). Not sure if the bug is in ProfileView or Cairo. I'm opening an issue in Cairo as it seems better maintained.

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaGraphics/Cairo.jl/pull/254
