### ISSUE TITLE
Doesn't work in Ubuntu

### ISSUE THREAD

**Issue by SimonEnsemble** [timholy/ProfileView.jl#93]
Upon `ProfileView.view()`, a dialog pops up that is very tiny, on Ubuntu 16.04, Julia v0.6.2.
If I hover over a region or click on it, nothing happens. So I can't see to which lines of code each colored region represents.

Here is an image of what it looks like:
![profile_view](https://user-images.githubusercontent.com/30643894/38710996-f1487d30-3e77-11e8-9207-14c5c497675d.png)

When I do click on a region, my Julia client shows: 
```
./REPL.jl, macro expansion: line 97
  ./event.jl, #1: line 73
```

**Comment by maxlarsen** [comment]
And here.

**Comment by floswald** [comment]
same here on macOS. (my REPL shows nothing when I click on the graph. the graph doesn't display any function names or anything either)

**Comment by rafaqz** [comment]
Same on arch linux

**Comment by antoine-levitt** [comment]
This is https://github.com/timholy/ProfileView.jl/issues/91. Someone needs to take care of https://github.com/JuliaGraphics/Cairo.jl/issues/223, but in the meantime a workaround is 
```julia
Pkg.pin("Cairo", v"0.4.0")
Pkg.update()
```

**Comment by floswald** [comment]
awesome @antoine-levitt ! works. thanks for checking back.

**Comment by liuzheng1990** [comment]
@antoine-levitt Wonderful! Verified on Ubuntu 16.04.

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaGraphics/Cairo.jl/pull/254
