### ISSUE TITLE
Jupyterlab compatibility

### ISSUE THREAD

**Issue by rdeits** [timholy/ProfileView.jl#94]
ProfileView seems to display the profile correctly inside jupyterlab, but the function labels are missing and the panning, zooming, and mouseover effects don't work. I suspect this is because jupyterlab does not execute inline javascript.

**Comment by cossio** [comment]
I am having the same issue.

**Comment by timholy** [comment]
Since I don't know javascript, fixing this is not on my agenda, but I would appreciate a pull request.

**Comment by jlumpe** [comment]
As another workaround you can open the image in a new tab for the mouseover to work.

**Comment by cossio** [comment]
@jlumpe How do you open it in a new tab?

**Comment by jlumpe** [comment]
@cossio I can't remember exactly because this was three months ago and I haven't used it since then, but I think the output is an SVG image so (in Chrome at least) you can right click on it and select "Open image in new tab."

**Comment by timholy** [comment]
Jupyter/SVG support moved to https://github.com/timholy/ProfileSVG.jl
